### ISSUE TITLE
wrong manipulation of shashes in some fields

### ISSUE THREAD

**Issue by mosoriob** [mintproject/ModelCatalog#33]

**Comment by dgarijo** [comment]
For example in economicGambella-v6.1 the description "ethiopia)          The price index still comes from the World Food Programme report, which   included Gambella and its own set of prices.          The Nitrogen application rate is set to a low value because farmers in   Gambella utilize very low level of fertilizer.       All other parameters, have been approximate based the South Sudan model   calibration"

The right field description is:
Aggregate crop supply response model for the country of South Sudan (version 6.1). Based on the Agricultural Sample Survey reports (AgSS), two crops are harvested in this region: maize and sorghum, so this model includes only 2 crops. Land use, production and yield level data comes from Agss report 2014 (http://surveys.worldbank.org/lsms/programs/integrated-surveys-agriculture-ISA/ethiopia) The price index still comes from the World Food Programme report, which included Gambella and its own set of prices. The Nitrogen application rate is set to a low value because farmers in Gambella utilize very low level of fertilizer. All other parameters, have been approximate based the South Sudan model calibration.
